spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api/v1/

mybatis:
  type-aliases-package: com.pengfu.mynav.model.entity
  configuration:
    map-underscore-to-camel-case: true